export const PRODUCTSDATA = {
    saltProductId:  { img: 'https://i.postimg.cc/mr41T347/salt.png', price: 3.87, name: "Salt", productId: 'saltProductId'},
    bonelessChickenProductId: { img: 'https://i.postimg.cc/jdJDN3dz/chicken.jpg', price: 5.94, name: "Boneless Chicken", productId: 'bonelessChickenProductId'},
    blackPepperProductId: { img: 'https://i.postimg.cc/Z5tCLPCX/pepper.jpg', price: 3.18, name: "Black pepper", productId: 'blackPepperProductId'},
    swissCheeseProductId: { img: 'https://i.postimg.cc/W1GtYDZz/cheese.jpg', price: 1.84, name: "Swiss cheese", productId: 'swissCheeseProductId'},
    cookedHamProductId: { img: 'https://i.postimg.cc/FKhzM9bZ/ham.png', price: 3.97, name: "Cooked Ham", productId: 'cookedHamProductId'},
    breadCrumbsProductId:{ img: 'https://i.postimg.cc/YS80kJbw/bread-crumbs.jpg', price:8.00, name: "Bread crumbs", productId: 'breadCrumbsProductId'},
    salmonProductId:{ img: 'https://i.postimg.cc/T153VhGR/salmon.jpg', price: 2.22, name: "Salmon", productId: 'salmonProductId'},
    mustardProductId: { img: 'https://i.postimg.cc/Jtw4Pm4j/mustard.jpg', price: 1.97,name: "Mustard", productId: 'mustardProductId'},
    butterProductId: { img: 'https://i.postimg.cc/xjBKWzX3/butter.jpg', price: 3.42,name: "Butter", productId: 'butterProductId'},
    eggsProductId: { img: 'https://i.postimg.cc/PxgmZjR7/eggs.jpg',price: 3.67, name: "Organic eggs", productId: 'eggsProductId'},
    rosemaryProductId:{ img: 'https://i.postimg.cc/tC283v95/rosemary.png',price: 0.99, name: "Rosemary", productId: 'rosemaryProductId'},
    lemonProductId: { img: 'https://i.postimg.cc/pXfz43mf/lemon.jpg', price: 2.99, name: "Lemon", productId: 'lemonProductId'},
    garlicProductId: { img: 'https://i.postimg.cc/jdJFGqTD/garlic.png', price: 2.45, name: "Garlic", productId: 'garlicProductId'},
    spaghettiProductId: { img: 'https://i.postimg.cc/prkzSFdw/spaghetti.jpg',price: 1.67, name: "Spaghetti", productId: 'spaghettiProductId'},
    potatoProductId: { img: 'https://i.postimg.cc/VsZ3cz7f/potato.jpg', price: 5.94,name: "Potato", productId: "potatoProductId"},
    creamProductId: { img: 'https://i.postimg.cc/k5ypYC6d/cream.png', price: 1.87,name: "Cream", productsId:"creamProductId"},
    vegetableOilProductId: { img: 'https://i.postimg.cc/tC283v95/rosemary.png',price: 0.99, name: "Vegetable oil",productId:"vegetableOilProductId"},
    sausagesProductId: { img: 'https://i.postimg.cc/k4Pcqbx3/brown-rice.png', price: 2.45, name: "Sausages",productId:"sausagesProductId"},
    gingerMarmaladeProductId: { img: 'https://i.postimg.cc/6QTvgLT5/Buderim-Ginger-Original-Marmalade.jpg', price: 5.94,name: "Ginger marmalade",productsId:"gingerMarmaladeProductId"},
    carrotProductId: { img: 'https://i.postimg.cc/76cKGZJw/carrot.jpg', price: 1.87,name: "Carrot", productId:"carrotProductId"},
    baconProductId: { img: 'https://i.postimg.cc/6ptVjvdy/sausageproduct.png',price: 0.99, name: "Bacon", productId: "baconProductId"},
    blackBeansProductId: { img: 'https://i.postimg.cc/R07t1bny/blackbeans.png', price: 5.94,name: "Black beans",productId: 'blackBeansProductId'},
    brownRiceProductId: { img: 'https://i.postimg.cc/k4Pcqbx3/brown-rice.png', price: 2.45, name: "Brown rice", productId: "brownRiceProductId"},
}